name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    # 🚨 Update the Ubuntu version to match the server you're deploying to. See
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # for supported versions.
    runs-on: ubuntu-latest
    services:
      # 🚨 Update the Postgres version and database name to match your app environment and test config
      postgres:
        image: postgres:10.19
        env:
          POSTGRES_DB: travis
          POSTGRES_HOST_AUTH_METHOD: trust    
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    # 🚨 Update the Python version to match your app environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: set up settings
      run: mv configs/local_settings.travis.py bga_database/local_settings.py 
    - name: Tests
      # 🚨 Swap in the correct filenames for your test and application configs
      run: |
        flake8
        python manage.py migrate
  deploy:
    needs: test
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@0.2.2
        with:
          # 🚨 Swap in your CodeDeploy application name, which is usually the same as the repository name
          application: bga-pensions
